import type { Transaction } from "../types/transaction";

export const transactions: Transaction[] = [
  {
    id: "txn_001",
    date: "2026-09-22",
    description: "AWS Cloud Services",
    vendor: "Amazon Web Services",
    category: "Software",
    amount: 12400,
    type: "expense",
    status: "completed",
    paymentMethod: "Corporate Card",
  },
  {
    id: "txn_002",
    date: "2026-09-21",
    description: "Slack Business Plan",
    vendor: "Slack",
    category: "Software",
    amount: 8200,
    type: "expense",
    status: "completed",
    paymentMethod: "Corporate Card",
  },
  {
    id: "txn_003",
    date: "2026-09-20",
    description: "Client Payment",
    vendor: "Acme Corporation",
    category: "Revenue",
    amount: 85000,
    type: "income",
    status: "completed",
    paymentMethod: "Bank Transfer",
  },
  {
    id: "txn_004",
    date: "2026-09-19",
    description: "Uber Business Travel",
    vendor: "Uber",
    category: "Travel",
    amount: 2400,
    type: "expense",
    status: "pending",
    paymentMethod: "Corporate Card",
  },
  {
    id: "txn_005",
    date: "2026-09-18",
    description: "Office Supplies",
    vendor: "Office Depot",
    category: "Office",
    amount: 5600,
    type: "expense",
    status: "completed",
    paymentMethod: "Corporate Card",
  },
  {
    id: "txn_006",
    date: "2026-09-17",
    description: "Google Workspace",
    vendor: "Google",
    category: "Software",
    amount: 7200,
    type: "expense",
    status: "completed",
    paymentMethod: "Corporate Card",
  },
  {
    id: "txn_007",
    date: "2026-09-16",
    description: "Figma Professional",
    vendor: "Figma",
    category: "Software",
    amount: 4100,
    type: "expense",
    status: "completed",
    paymentMethod: "Corporate Card",
  },
  {
    id: "txn_008",
    date: "2026-09-15",
    description: "Hotel Accommodation",
    vendor: "Marriott",
    category: "Travel",
    amount: 9800,
    type: "expense",
    status: "pending",
    paymentMethod: "Corporate Card",
  },
  {
    id: "txn_009",
    date: "2026-09-14",
    description: "Consulting Revenue",
    vendor: "Globex Inc",
    category: "Revenue",
    amount: 62000,
    type: "income",
    status: "completed",
    paymentMethod: "Bank Transfer",
  },
  {
    id: "txn_010",
    date: "2026-09-13",
    description: "AWS Cloud Services",
    vendor: "Amazon Web Services",
    category: "Software",
    amount: 11800,
    type: "expense",
    status: "failed",
    paymentMethod: "Corporate Card",
  },
  {
    id: "txn_011",
    date: "2026-09-12",
    description: "Team Lunch",
    vendor: "FreshMenu",
    category: "Food",
    amount: 3200,
    type: "expense",
    status: "completed",
    paymentMethod: "Corporate Card",
  },
  {
    id: "txn_012",
    date: "2026-09-11",
    description: "Adobe Creative Cloud",
    vendor: "Adobe",
    category: "Software",
    amount: 6300,
    type: "expense",
    status: "completed",
    paymentMethod: "Corporate Card",
  },
];